#!/bin/sh -e

# Disable gettext
sed -i 's/po\/Makefile.in//' configure.ac
sed -i '/GETTEXT_PACKAGE/d' configure.ac
sed -i '/AM_GNU_GETTEXT/d'  configure.ac
sed -i 's/po\b//'            Makefile.am
sed -i '/@LIBINTL@/d'        src/Makefile.am

autoreconf -i
./configure --prefix="/usr"
make
make install DESTDIR="$1"
